
# -*- coding: utf-8 -*-
"""
Initially Generated By:
    python -m utool --tf setup_repo --repo=pyhesaff --codedir=~/code --modname=pyhesaff
"""
from __future__ import absolute_import, division, print_function, unicode_literals


def pyhesaff_main():
    ignore_prefix = []
    ignore_suffix = []
    import utool as ut
    ut.main_function_tester('pyhesaff', ignore_prefix, ignore_suffix)

if __name__ == '__main__':
    """
    Usage:
        python -m pyhesaff --tf <funcname>
        python -m pyhesaff <funcname>
    """
    print('Running pyhesaff main')
    pyhesaff_main()
